Add juniper.bot translation
PreMiD/Localization pull request #4340
Opened 2020-12-27 15:11 UTC by MrLivixx

2020-12-27 16:38 UTC, Bas950 requested changes

2020-12-27 16:38 UTC, Bas950 commented on src/Presence/juniperbot.json
> +    },
description correct?

2020-12-27 16:38 UTC, Bas950 commented on src/Presence/juniperbot.json
> +    }
Not needed, you can use "general.reading" as the general.json file is always counted too.

2020-12-27 17:20 UTC, MrLivixx commented
Fixed

2020-12-28 01:19 UTC, Bas950 commented
Aight looking good now, please link the pr of the presence update in here when ready

2020-12-28 10:09 UTC, MrLivixx commented
> Aight looking good now, please link the pr of the presence update in here when ready

https://github.com/PreMiD/Presences/pull/2707

2020-12-28 12:46 UTC, Bas950 requested changes

2020-12-28 12:46 UTC, Bas950 commented on src/Presence/juniperbot.json
> +    },
Use "general.reading" + "general.terms"

2020-12-28 12:46 UTC, Bas950 commented on src/Presence/juniperbot.json
> +    },
Use "general.reading" + "general.privacy"

2020-12-28 12:46 UTC, Bas950 commented on src/Presence/juniperbot.json
> +    },
Duplicate strings?

2020-12-28 15:26 UTC, MrLivixx commented
Fixed it

2020-12-28 17:30 UTC, Bas950 requested changes
After this you should be good to go

2020-12-28 17:30 UTC, Bas950 commented on src/Presence/juniperbot.json
> +      "description": "Reads about the site's cookies"
Reading about sounds better.

2020-12-28 17:30 UTC, Bas950 commented on src/Presence/juniperbot.json
> +      "description": "Guild name"
use {0} instead

2020-12-28 17:30 UTC, Bas950 commented on src/Presence/juniperbot.json
> +      "description": "Page with information about donation plans"
about **the** donation plans

2020-12-28 17:55 UTC, merged