🎨  Localisation Support
PreMiD/Localization pull request #6094
Opened 2021-03-08 19:54 UTC by EncryptedDev

Adds support for: 
- Google Classroom
- Google Docs

2021-03-08 21:19 UTC, ImRodry requested changes

2021-03-08 21:19 UTC, ImRodry commented on src/Website/google classroom.json
> +    "description": "Displayed when the user is viewing an assignment and their privacy mode is on"
Explain what "privacy mode is on" means

2021-03-08 21:19 UTC, ImRodry commented on src/Website/google classroom.json
> +    "message": "Viewing to do list",
```suggestion
    "message": "Viewing their to-do list",
```

2021-03-08 21:19 UTC, ImRodry commented on src/Website/google classroom.json
> +    "message": "Viewing an assignment in",
Add : to all strings that have "in" or "of" for consistency

2021-03-08 21:19 UTC, ImRodry commented on src/Website/google docs.json
> +        "message": "Browsing Forms",
Consistency with upper/lower case

2021-03-08 21:19 UTC, ImRodry commented on src/Website/google docs.json
> +        "message": "Editing a slidesheet",
```suggestion
        "message": "Editing a presentation",
```
Use the name used by Google on its website (same for the other strings)

2021-03-08 21:22 UTC, EncryptedDev commented on src/Website/google classroom.json
> +    "description": "Displayed when the user is viewing an assignment and their privacy mode is on"
Privacy mode is a setting within the presence which disables other users from being able to see the class name etc
Look at the [PR](https://github.com/PreMiD/Presences/pull/3203) to see what it does, in terms of screenshots

2021-03-08 21:26 UTC, ImRodry commented on src/Website/google classroom.json
> +    "message": "Viewing an assignment in",
Sorry I believe you misunderstood, I was asking you to add ":" to the end of these strings

2021-03-08 21:28 UTC, EncryptedDev commented on src/Website/google classroom.json
> +    "message": "Viewing an assignment in",
oh kekw let me revert

2021-03-08 21:28 UTC, ImRodry commented on src/Website/google classroom.json
> +    "description": "Displayed when the user is viewing an assignment and their privacy mode is on"
Yeah I know but it may be harder for translations to understand so I think you should give a slightly more detailed explanation.
```suggestion
    "description": "Displayed when the user is viewing an assignment and they chose to share the name of the assignment"
```
Doesn't need to be this because I'm not sure if that's fully correct but something along these lines

2021-03-08 21:35 UTC, EncryptedDev commented on src/Website/google classroom.json
> +    "description": "Displayed when the user is viewing an assignment and their privacy mode is on"
Would this be much better?

Displayed when the user is viewing an assignment and their privacy mode is on (privacy mode is a setting within the presence to hide sensitive, in this case, assignment)

2021-03-08 21:38 UTC, ImRodry commented on src/Website/google classroom.json
> +    "description": "Displayed when the user is viewing an assignment and their privacy mode is on"
Yep, sounds good. You can use that to all strings that use privacy mode

2021-03-08 21:53 UTC, ImRodry requested changes

2021-03-08 21:53 UTC, ImRodry commented on src/Website/google classroom.json
> +    "description": "Displayed when a user is viewing classwork"
Explain what comes after "of:" in all instances (I'm assuming the name of a class) in the context.

2021-03-08 21:53 UTC, ImRodry commented on src/Website/google docs.json
> +        "description": "Displayed when the user is editing a Google Slide"
```suggestion
        "description": "Displayed when the user is editing a Google Presentation"
```
More consistency

2021-03-08 22:09 UTC, ImRodry requested changes
Missed consistency

2021-03-08 22:09 UTC, ImRodry commented on src/Website/google docs.json
> +        "description": "Displayed when the user is browsing their Google Slides"
```suggestion
        "description": "Displayed when the user is browsing their Google Presentations"
```

2021-03-08 22:18 UTC, ImRodry approved these changes

2021-03-08 22:31 UTC, Bas950 requested changes

2021-03-08 22:31 UTC, Bas950 commented on src/Website/google classroom.json
> +  },
I checked your code, you could just use general.viewHome

2021-03-08 23:13 UTC, EncryptedDev commented on src/Website/google classroom.json
> +  },
Sure, let me remove it

2021-03-08 23:42 UTC, Bas950 requested changes

2021-03-08 23:42 UTC, Bas950 commented on src/Website/google docs.json
> +
remove the extra enter xD

2021-03-09 00:24 UTC, Bas950 approved these changes

2021-03-09 00:26 UTC, merged