Create animepahe.json
PreMiD/Localization pull request #6668
Opened 2021-06-28 23:43 UTC by MulverineX

![image](https://user-images.githubusercontent.com/12068027/123716632-558cef80-d838-11eb-9d09-7a745fb3a406.png)

2021-06-29 20:23 UTC, Bas950 requested changes
A lot of your strings are unneeded as they are in the general.json file

2021-07-08 18:04 UTC, Bas950 requested changes

2021-07-08 18:04 UTC, Bas950 commented on src/Presence/animepahe.json
> +  },
Seems unneeded to me

2021-07-08 18:04 UTC, Bas950 commented on src/Presence/animepahe.json
> +  },
add description

2021-07-08 18:04 UTC, Bas950 commented on src/Presence/animepahe.json
> +  },
```suggestion
  "animepahe.view": {
    "message": "View on {0}",
    "description": "{0} will be replaced by Pahe/AniList"
  },
```

2021-07-08 18:04 UTC, Bas950 commented on src/Presence/animepahe.json
> +  },
![image](https://user-images.githubusercontent.com/34792838/124969965-a3b7a500-e027-11eb-809b-19b182758b69.png)
Already strings for that available

2021-07-08 18:04 UTC, Bas950 commented on src/Presence/animepahe.json
> +  },
Content?

2021-07-08 19:03 UTC, MulverineX commented on src/Presence/animepahe.json
> +  },
There's no "Watch Movie"

2021-07-08 19:04 UTC, MulverineX commented on src/Presence/animepahe.json
> +  },
What about languages that are not latin based

2021-07-08 22:24 UTC, MulverineX commented on src/Presence/animepahe.json
> +  },
What?

2021-07-10 14:52 UTC, Bas950 requested changes

2021-07-10 14:52 UTC, Bas950 commented on src/Presence/animepahe.json
> +  },
Still seems unneeded to me

2021-07-10 14:52 UTC, Bas950 commented on src/Presence/animepahe.json
> +  },
Then add it to general.json as it can be used more often

2021-07-10 14:52 UTC, Bas950 commented on src/Presence/animepahe.json
> +  },
Context*

2021-07-11 09:42 UTC, Bas950 requested changes
That should be it

2021-07-11 09:42 UTC, Bas950 commented on src/Presence/animepahe.json
> +  "animepahe.browsingHome": {
```suggestion
  "animepahe.latestRelease": {
```

2021-07-11 09:42 UTC, Bas950 commented on src/Presence/animepahe.json
> +  "animepahe.browsingSpecial": {
```suggestion
  "animepahe.special": {
```

2021-07-11 09:42 UTC, Bas950 commented on src/Presence/animepahe.json
> +  "animepahe.browsingSeason": {
```suggestion
  "animepahe.season": {
```

2021-07-11 09:42 UTC, Bas950 commented on src/Presence/animepahe.json
> +    "description": "{0} will be replaced by Pahe or AniList"
```suggestion
    "description": "{0} will be replaced by \"Pahe\" or \"AniList\""
```

2021-07-11 17:23 UTC, merged