feat(kahoot): Add and modify messages
PreMiD/Localization pull request #7084
Opened 2022-03-26 02:09 UTC by theusaf

https://github.com/PreMiD/Presences/pull/5975

2022-03-26 14:29 UTC, ImRodry requested changes

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Looking at Slide with Content...",
either undo this or remove the ...

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Showing Slide with Content...",
ditto

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used to display the position (ranking) of a player. {0} is the position"
this should include an example. Also remove the second sentence as its quite redundant

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Discussing with Tean...",
english...
```suggestion
        "message": "Discussing with team",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Game Locked",
where does this appear?

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Looking at Game Summary...",
```suggestion
        "message": "Looking at game summary...",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Create Home Page...",
```suggestion
        "message": "Viewing Create Home Page",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Kahoot! Discover Page...",
```suggestion
        "message": "Viewing Kahoot! Discover Page",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is searching for Kahoots"
will this show the search query below? If so, mention it

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Kahoot Details:",
```suggestion
        "message": "Viewing Kahoot details",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is viewing the details of a Kahoot"
ditto

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Kahoot Profile:",
```suggestion
        "message": "Viewing Kahoot profile",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing My Kahoots...",
```suggestion
        "message": "Viewing their Kahoots",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Game Reports...",
```suggestion
        "message": "Viewing game reports",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing My Courses...",
```suggestion
        "message": "Viewing their courses",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Editing a Course:",
You either wanna say they're editing a course or what course they're editing, not both at the same time. Depending on which one it is you should remove the colon or adjust the wording accordingly. Also remove the unnecessary capital letter

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing a Course:",
ditto

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Editing a Kahoot:",
ditto

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Previewing a Kahoot...",
ditto

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Conducting a Live Course...",
ditto

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Summary: {0}",
The title of the course should go on the presence state instead
```suggestion
        "message": "Viewing Summary for",
```

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used to display the title of the course being conducted. {0} is the title of the course"
second sentence is redundant

2022-03-26 14:29 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Doing Activity: #{0}: {1}",
way too many colons

2022-03-26 17:10 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Game Locked",
This appears in the button text in the presence when in the lobby, but the host has locked the game, preventing people from joining.

2022-03-26 17:17 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Game Locked",
Screenshot please

2022-03-26 17:23 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Game Locked",
Decided to remove this, I just won't show the button if the game is locked.

2022-03-26 17:26 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Viewing Kahoot Details:",
If I'm displaying the Kahoot details in the state (below), should I keep the colon or remove it?

2022-03-26 17:28 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Kahoot Details:",
keep it ig but I don't see why you would do that

2022-03-26 17:30 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Viewing Summary: {0}",
Removing, as this seems to be redundant.

2022-03-26 17:32 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Activity #{0}: {1}",
Changed to this, as this string will be used in the presence state.

2022-03-26 17:35 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Editing a Course:",
This message will be the details of the presence, and the course they are editing is in the state. Added this detail to the description.

2022-03-26 20:19 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Activity #{0}: {1}",
please show a screenshot of this

2022-03-26 21:52 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Activity #{0}: {1}",
<img width="960" alt="2022-03-26 14_50_36" src="https://user-images.githubusercontent.com/32113157/160258282-5d131671-48eb-40f4-8577-f374ca35cd99.png">
<img width="225" alt="2022-03-26 14_50_52" src="https://user-images.githubusercontent.com/32113157/160258283-d76f1944-0d8f-41c4-9408-a709785e10b8.png">
<img width="222" alt="2022-03-26 14_52_11" src="https://user-images.githubusercontent.com/32113157/160258284-227bc40d-0c0c-4324-93b4-227e8a5575e3.png">

2022-03-29 17:35 UTC, ImRodry requested changes

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Answered Poll",
Has answered or the poll is answered? Please show a screenshot where this is used

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Create home page",
I believe this is better @Bas950 wdyt (would apply the same pattern for the ones below)
```suggestion
        "message": "Viewing the \"Create home\" page",
```

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing Kahoot details:",
shouldn't it be like this
```suggestion
        "message": "Viewing details of Kahoot:",
```

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is viewing their own courses"
what's a course in kahoot?

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Editing a course:",
```suggestion
        "message": "Editing course:",
```

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing a course:",
```suggestion
        "message": "Viewing course:",
```

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Editing a Kahoot:",
why was this resolved?
```suggestion
        "message": "Editing Kahoot:",
```

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
why doesn't this show the name of the kahoot like the others?

2022-03-29 17:35 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is conducting a live course"
~~no shit sherlock~~ this should give a brief explanation on what a live course is

2022-03-30 00:51 UTC, theusaf commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
It would require accessing iFrame data, the name of the Kahoot is not available in this case.

2022-03-30 00:53 UTC, theusaf commented on src/Presence/kahoot.json
> +        "description": "Used when the user is viewing their own courses"
A course is a new feature on create.kahoot.it where multiple kahoots and other third-party activities can be grouped together.

2022-03-30 01:07 UTC, theusaf commented on src/Presence/kahoot.json
> +        "description": "Used when the user is conducting a live course"
Added an explanation. Does the newer explanation need any changes?

2022-03-30 01:13 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Answered Poll",
<img width="227" alt="2022-03-29 18_13_14" src="https://user-images.githubusercontent.com/32113157/160731322-136d4ec2-ab7a-4b71-af68-7f7555d4320b.png">
<img width="960" alt="2022-03-29 18_13_22" src="https://user-images.githubusercontent.com/32113157/160731323-67eb4338-2534-44cc-9f6b-6b0654df4422.png">

2022-03-30 01:51 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Editing a Kahoot:",
Should be correct now.

2022-03-30 04:47 UTC, Bas950 commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
Cant you just get it out of the iframe?

2022-03-30 04:47 UTC, Bas950 commented on src/Presence/kahoot.json
> +        "message": "Viewing Create home page",
Agreed

2022-03-30 05:17 UTC, theusaf commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
I'll look into this.

2022-03-30 05:34 UTC, theusaf commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
This would be a bit tricky, as the name of the Kahoot being previewed is not always there. (The iframes are the `play.kahoot.it` and `kahoot.it` embedded into one page on `create.kahoot.it`)
An option I could do is to have the same presence show up, as though it were just `play.kahoot.it`, and have an icon mentioning that the user is also previewing the page.

2022-03-30 22:12 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Answered Poll",
this doesn't make much sense IMO. The text would end up saying "Looking at results: Answered poll". What's the goal here?

2022-03-30 22:20 UTC, ImRodry requested changes

2022-03-30 22:20 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used to display the position (ranking) of a player. For example, 'Position: 2'"
```suggestion
        "description": "Used to display the position (ranking) of a player. For example, \"Position: 2\""
```

2022-03-30 22:20 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing the \"Create home\" page",
to be fair the page is called home on the website, don't know where you got this from. It could be changed to this which sounds more natural
```suggestion
        "message": "Viewing the home page",
```

2022-03-30 22:20 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing the \"Kahoot! Discover\" page",
again, page is just called Discover, don't know where you got this from
```suggestion
        "message": "Viewing the \"Discover\" page",
```

2022-03-30 22:20 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is viewing their game reports"
consistency (assuming this is true)
```suggestion
        "message": "Viewing their game reports",
        "description": "Used when the user is viewing their own game reports"
```

2022-03-30 22:20 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
iframe.ts is for gathering any data from an iframe. Ig it's up to you if you wanna do it but if you've figured it out I don't see why not

2022-03-30 22:54 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Answered Poll",
That's fair. It was just to fill in the state, although it probably doesn't need it. I'll remove this string.

2022-03-30 22:56 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Viewing the \"Create home\" page",
The reason I added "Create" to the string is that it's the homepage for specifically `create.kahoot.it`, to avoid ambiguity.

2022-03-30 23:09 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "message": "Viewing the \"Create home\" page",
You could provide info about the url elsewhere maybe? Not sure if they have different icons but maybe through a state or small image text?

2022-03-31 00:58 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
Why doesn’t the name go in the state? Also if you specify the name the string needs to be changed

2022-03-31 01:02 UTC, theusaf commented on src/Presence/kahoot.json
> +        "message": "Viewing the \"Create home\" page",
They have the same icon, but I'll consider some kind of small image alternative.

2022-03-31 05:29 UTC, theusaf commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
Okay. Found a way to display just the name.
<img width="221" alt="2022-03-30 22_28_33" src="https://user-images.githubusercontent.com/32113157/160983065-a6854548-f826-46fd-825e-4c72a3646b9c.png">

2022-04-02 00:07 UTC, ImRodry requested changes
final review, just address these two things and this can be merged

2022-04-02 00:07 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is previewing a Kahoot"
```suggestion
        "description": "Used when the user is previewing a Kahoot. The name of the Kahoot will be displayed below."
```

2022-04-02 00:07 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when a player is providing feedback to the host"
feedback about ...? the course?
```suggestion
        "description": "Used when a player is providing feedback about the course to the host"
```

2022-04-02 09:31 UTC, ImRodry requested changes

2022-04-02 09:31 UTC, ImRodry commented on src/Presence/kahoot.json
> +        "description": "Used when the user is viewing the profile of a Kahoot"
Sorry I didn’t notice this. Is this the profile of a player? If so, what will you display below? Should probs mention that

2022-04-02 16:51 UTC, Bas950 commented on src/Presence/kahoot.json
> +        "description": "Used to display the activity being conducted."
this should be explained better, especially what 0 and 1 are...

2022-04-02 16:57 UTC, ImRodry approved these changes
After @Bas950's review this LGTM

2022-04-03 07:53 UTC, Bas950 approved these changes

2022-04-03 07:53 UTC, merged