add language file for upcoming rewrite of osu!ppy
PreMiD/Localization pull request #7189
Opened 2022-07-25 07:35 UTC by StrikerFRFX

2022-07-28 21:41 UTC, EncryptedDev requested changes

2022-07-28 21:41 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  },
Add this to general as it can be use universally

2022-07-28 21:41 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  },
```suggestion
  "osu!ppy.viewingNews": {
    "message": "Viewing News Articles",
    "description": "Displayed when viewing all osu! news."
  },
```

2022-07-28 21:41 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  },
```suggestion
  "osu!ppy.viewNews": {
    "message": "View News Article",
    "description": "Displayed for a button to redirect to the news page."
  },
```

2022-07-28 21:41 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  },
```suggestion
  "osu!ppy.beatMapListing": {
    "message": "Viewing Beatmap Listings",
    "description": "Displayed when viewing all beatmaps."
  },
```

2022-07-28 21:41 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  },
```suggestion
  "osu!ppy.beatMapPacks": {
    "message": "Viewing Beatmap Packs",
    "description": "Displayed when viewing all beatmap packs."
  },
```

2022-07-28 21:41 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  },
```suggestion
  "osu!ppy.beatMapLooking": {
    "message": "Looking at Beatmap",
    "description": "Displayed when looking at a beatmap."
  },
```

2022-07-28 21:41 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  },
```suggestion
  "osu!ppy.beatmapRankings": {
    "message": "Viewing Kudosu Rankings",
    "description": "Displayed when viewing Kudosu Rankings."
  },
```

2022-07-28 21:41 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  }
This should be "View Wiki" and moved to general

2022-07-30 15:36 UTC, StrikerFRFX commented on src/Presence/osu!ppy.json
> +  }
Not used for a button, would be "Viewing Wiki"

2022-07-31 08:01 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  },
Not resolved

2022-07-31 08:02 UTC, EncryptedDev commented on src/Presence/osu!ppy.json
> +  }
OK, you should still add a verb to it

2022-07-31 16:29 UTC, StrikerFRFX commented on src/Presence/osu!ppy.json
> +  }
It counts as the same as Support so no verb

2022-08-16 12:41 UTC, EncryptedDev commented
Closed until PreMiD/Presences PR is created

2022-10-16 00:30 UTC, StrikerFRFX commented
Reopen

2022-10-16 20:14 UTC, theusaf commented
https://github.com/PreMiD/Presences/pull/6893

2023-03-25 13:43 UTC, DarkVillager commented
#7285

2023-03-26 17:58 UTC, closed without merging