feat(Youtube): change & add strings
PreMiD/Localization pull request #7268
Opened 2023-03-06 14:15 UTC by DarkVillager

2023-03-06 20:15 UTC, Bas950 requested changes

2023-03-06 20:15 UTC, Bas950 commented on src/Presence/youtube.json
> +	},
Add a description that has information about what {0} will be replaced with

2023-03-06 20:25 UTC, DarkVillager commented on src/Presence/youtube.json
> +	},
the topic

2023-03-09 20:56 UTC, Bas950 approved these changes

2023-03-26 17:58 UTC, merged