feat(osu!ppy): add language file
PreMiD/Localization pull request #7285
Opened 2023-03-25 13:41 UTC by DarkVillager

feat: add more strings

2023-03-26 18:01 UTC, Bas950 requested changes

2023-03-26 18:01 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +		"message": "Reading News:"
would probably be good as a general string.

2023-03-26 18:01 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +		"message": "Support"
general.support ?

2023-03-26 18:01 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +	}
Could all be good as general strings

2023-08-18 10:58 UTC, DarkVillager commented on src/Presence/osu!ppy.json
> +		"message": "Looking at Beatmap"
shows the title.

2023-08-18 11:01 UTC, DarkVillager commented on src/Presence/osu!ppy.json
> +		"message": "Support"
This will get changed.

2023-08-18 11:01 UTC, DarkVillager commented on src/Presence/osu!ppy.json
> +	}
Ok.

2023-08-25 10:11 UTC, Bas950 requested changes

2023-08-25 10:11 UTC, Bas950 commented on src/Presence/general.json
> +  },
Can't you just use Read Article?

2023-08-25 10:11 UTC, Bas950 commented on src/Presence/general.json
> +  },
Ditto

2023-08-25 10:11 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +  },
so what does 0 get replaced with?

2023-08-25 10:11 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +  },
Same here the description just isn't enough.

2023-08-25 10:11 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +  },
ditto

2023-08-29 10:37 UTC, DarkVillager commented on src/Presence/general.json
> +  },
You be the judge of that. Example url: [https://osu.ppy.sh/home/news/2023-08-29-changes-to-the-mappers-guild](https://osu.ppy.sh/home/news/2023-08-29-changes-to-the-mappers-guild)

2023-08-29 18:42 UTC, Bas950 commented on src/Presence/general.json
> +  },
I think you can

2023-08-29 18:43 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +  },
Please update the description to include information of the variable

2023-08-29 18:43 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +  },
Please update the description to include information of the variable

2023-08-29 18:43 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +  },
Please update the description to include information of the variable

2023-09-09 08:43 UTC, Bas950 requested changes

2023-09-09 08:43 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +		"message": "for {0} {1}"
Description states `(for All) [osu!]`
Message states `for {0} {1}`
Shouldn't there be rounded brackets around `for {0}` ?

2023-09-09 08:43 UTC, Bas950 commented on src/Presence/osu!ppy.json
> +		"message": "The {0} spotlights {1}"
Ditto

2023-09-09 16:21 UTC, Bas950 approved these changes

2023-09-09 16:23 UTC, Timeraa approved these changes

2023-09-09 16:23 UTC, merged